# Generated by Django 6.0.4 on 2026-04-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessRoleRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_read", models.BooleanField(default=False)),
                ("can_read_all", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_edit_all", models.BooleanField(default=False)),
                ("can_create", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("can_delete_all", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_date", models.DateTimeField()),
                ("check_out_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In progress"),
                            ("finished", "Finished"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="new",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BusinessElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("role", "Role"),
                            ("hotel", "Hotel"),
                            ("room", "Room"),
                            ("review", "Review"),
                            ("reviewReply", "Reply"),
                            ("booking", "Booking"),
                            ("accessRoleRules", "Access Role Rules"),
                        ],
                        unique=True,
                    ),
                ),
                ("description", models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("location", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("1", "1/5"),
                            ("2", "2/5"),
                            ("3", "3/5"),
                            ("4", "4/5"),
                            ("5", "5/5"),
                        ]
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReviewReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("guest", "Guest"),
                            ("hotel_manager", "Hotel manager"),
                            ("admin", "Admin"),
                        ],
                        unique=True,
                    ),
                ),
                ("description", models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
