# Generated by Django 6.0.4 on 2026-04-23 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="guest_id",
            field=models.ForeignKey(
                db_column="guest_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.user",
            ),
        ),
        migrations.AddField(
            model_name="accessrolerule",
            name="element_id",
            field=models.ForeignKey(
                db_column="element_id",
                on_delete=django.db.models.deletion.PROTECT,
                to="api.businesselement",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="manager_id",
            field=models.ForeignKey(
                db_column="manager_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.user",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="booking_id",
            field=models.ForeignKey(
                db_column="booking_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.booking",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="hotel_id",
            field=models.ForeignKey(
                db_column="hotel_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.hotel",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.user",
            ),
        ),
        migrations.AddField(
            model_name="reviewreply",
            name="manager_id",
            field=models.ForeignKey(
                db_column="manager_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reply",
                to="authentication.user",
            ),
        ),
        migrations.AddField(
            model_name="reviewreply",
            name="review_id",
            field=models.ForeignKey(
                db_column="review_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.review",
            ),
        ),
        migrations.AddField(
            model_name="accessrolerule",
            name="role_id",
            field=models.ForeignKey(
                db_column="role_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.role",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="hotel_id",
            field=models.ForeignKey(
                db_column="hotel_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.hotel",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="room_id",
            field=models.ForeignKey(
                db_column="room_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.room",
            ),
        ),
    ]
