# Generated by Django 6.0.4 on 2026-04-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("guest", "Guest"),
                    ("receptionist", "Receptionist"),
                    ("hotel_manager", "Hotel manager"),
                    ("admin", "Admin"),
                ],
                unique=True,
            ),
        ),
    ]
